#include <stdio.h>
#include <stdlib.h>
#include <time.h>

/* run this program using the console pauser or add your own getch, system("pause") or input loop */

int main() {      //declares the main function, which is the starting point of the program
	int n;        //declares a variable n of type int 
	
	printf("random number in [1,6]\n");  //prints the string "random number in [1,6]" to the console 
	
	srand(time(NULL));   /*seeds the random number generator with the current time. 
	This ensures that the sequence of random numbers generated by the program will be different every time it's run.*/
	
	n = 1 + rand() % 6;  /*generates a random number in the range [1, 6]. 
	The rand function generates a random integer, and % 6 takes the modulus of that integer with 6 to get a value in the range [0, 5]. 
	Adding 1 to the result makes the range [1, 6]*/
	
	printf("%d\n", n);   //prints the value of n to the console
	
	return 0; //ends the main function and returns 0 to indicate successful completion of the program
	
} 
